apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: cmstx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq 
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: sandmanacrsandbox.azurecr.io/rabbitmq:v1  # Point to your ACR
        ports:
        - containerPort: 5672
        - containerPort: 15672 # Management UI
