# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

parameters:
  - name: environment
    displayName: 'Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - uat
      - prod
      - sandbox

  - name: subscriptionId
    displayName: 'Target Subscription ID'
    type: string
    default: ''

  - name: VMpassword  
    displayName: 'VMPassword'
    type: string
    default: ''

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: 'sandman-${{ parameters.environment }}-sc'
  location: 'southcentralus'
  resourceGroup: 'sandman-rg-${{ parameters.environment }}'
  parametersPath: 'infrastructure/parameters/${{ parameters.environment }}'

stages:
  - stage: Deploy
    displayName: 'Deploy ${{ parameters.environment }} Environment'
    jobs:
      - job: DeployInfrastructure
        steps:
          # Create Resource Group first
          - task: AzureCLI@2
            displayName: 'Create Resource Group'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create \
                  --subscription ${{ parameters.subscriptionId }} \
                  --name $(resourceGroup) \
                  --location $(location)

          # Create a Keyvault in that RG
          - task: AzureCLI@2
            displayName: 'Create Keyvault'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az keyvault create \
                  --subscription ${{ parameters.subscriptionId }} \
                  --resource-group $(resourceGroup) \
                  --name sandman-kv-${{ parameters.environment }} \
                  --location $(location) \
                  --enable-rbac-authorization true \
                  --public-network-access disabled \
                  --tags app=sandman \
                  --retention-days 7 || echo "keyvault already exists, skipping"


          # Deploy VNet into that RG
          - task: AzureCLI@2
            displayName: 'Validate VNet'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group what-if \
                  --subscription ${{ parameters.subscriptionId }} \
                  --resource-group $(resourceGroup) \
                  --template-file infrastructure/modules/vnet.bicep \
                  --parameters $(parametersPath)/vnet.params.json \
                  --parameters environment=${{ parameters.environment }} \
                  --parameters location=$(location)
                  

          - task: AzureCLI@2
            displayName: 'Deploy VNet'
            inputs:
               azureSubscription: $(serviceConnection)
               scriptType: 'bash'
               scriptLocation: 'inlineScript'
               inlineScript: |
                  output=$(az deployment group create \
                  --subscription ${{ parameters.subscriptionId }} \
                  --resource-group $(resourceGroup) \
                  --template-file infrastructure/modules/vnet.bicep \
                  --parameters $(parametersPath)/vnet.params.json \
                  --parameters environment=${{ parameters.environment }} \
                  --parameters location=$(location) \
                  --query 'properties.outputs' \
                  --output json)


                  vnetId=$(echo $output | jq -r '.vnetId.value')
                  subnetId=$(echo $output | jq -r '.peSubnetId.value')
                  echo "##vso[task.setvariable variable=vnetId;isOutput=true]$vnetId"
                  echo "##vso[task.setvariable variable=peSubnetId;isOutput=true]$subnetId"

            # deploy ACR
          - task: AzureCLI@2
            displayName: 'Deploy ACR'
            inputs:
               azureSubscription: $(serviceConnection)
               scriptType: 'bash'
               scriptLocation: 'inlineScript'
               inlineScript: |
                  az deployment group create \
                  --subscription ${{ parameters.subscriptionId }} \
                    --resource-group $(resourceGroup) \
                    --template-file infrastructure/modules/acr.bicep \
                    --parameters $(parametersPath)/acr.params.json \
                    --parameters environment=${{ parameters.environment }} \
                    --parameters location=$(location)
                    --parameters subnetId='$(deployVnet.peSubnetId)' \
                    --parameters vnetId='$(deployVnet.vnetId)'
