# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

parameters:
  - name: environment
    displayName: 'Environment'
    type: string
    default: 'dev'
    values:
      - dev
      - uat
      - qa
      - prod
      - sandbox

  - name: subscriptionId
    displayName: 'Target Subscription ID'
    type: string
    default: ''

  - name: VMpassword  
    displayName: 'VMPassword'
    type: string
    default: ''

pool:
  vmImage: ubuntu-latest

variables:
  serviceConnection: 'sandmansandbox'
  location: 'southcentralus'
  resourceGroup: 'sandman-rg-${{ parameters.environment }}'
  parametersPath: 'infrastructure/parameters/${{ parameters.environment }}'

stages:
  - stage: Deploy_Sandbox
    displayName: 'Deploy Sandbox Environment'
    jobs:
      - job: DeployInfrastructure
        steps:
          # Step 1 - Create Resource Group first
          - task: AzureCLI@2
            displayName: 'Create Resource Group'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create \
                  --subscription ${{ parameters.subscriptionId }} \
                  --name $(resourceGroup) \
                  --location $(location)

          # Step 2 - Create a Keyvault in that RG
          - task: AzureCLI@2
            displayName: 'Create Keyvault'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az keyvault create \
                  --subscription ${{ parameters.subscriptionId }} \
                  --resource-group $(resourceGroup) \
                  --name sandman-kv-${{ parameters.environment }} \
                  --location $(location) \
                  --enable-rbac-authorization true \
                  --public-network-access disabled \
                  --tags app=sandman

          # Step 3 - create keyvault secrets 
          - task: AzureCLI@2
            displayName: 'Create Keyvault Secrets'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az keyvault secret set \
                  --subscription ${{ parameters.subscriptionId }} \
                  --vault-name sandman-kv-${{ parameters.environment }} \
                  --name 'JumpboxAdminPassword' \
                  --value '${{ parameters.VMpassword }}'
                  


          # Step 4 - Deploy VNet into that RG
          - task: AzureCLI@2
            displayName: 'Validate VNet'
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment group what-if \
                  --subscription ${{ parameters.subscriptionId }} \
                  --resource-group $(resourceGroup) \
                  --template-file infrastructure/modules/vnet.bicep \
                  --parameters $(parametersPath)/vnet.params.json

          - task: AzureCLI@2
            displayName: 'Deploy VNet'
            inputs:
               azureSubscription: $(serviceConnection)
               scriptType: 'bash'
               scriptLocation: 'inlineScript'
               inlineScript: |
                  az deployment group create \
                    --subscription ${{ parameters.subscriptionId }} \
                    --resource-group $(resourceGroup) \
                    --template-file infrastructure/modules/vnet.bicep \
                    --parameters $(parametersPath)/vnet.params.json
