name: sandman-frontend
namespace: sandman
replicaCount: 1

image:
  repository: sandmanacrhub-brgyhrbngfbdfhba.azurecr.io/sandman-frontend
  tag: latest
  pullPolicy: Always

nodeSelector:
  kubernetes.io/arch: amd64

service:
  port: 30440
  targetPort: 80

runtimeConfig:
  configMapName: runtime-config-frontend
  configMapKey: runtime-config
  fileName: runtime-config.json
  mountPath: /usr/share/nginx/html/assets/config/runtime-config.json

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"
