name: sandman-frontend
namespace: sandman
replicaCount: 2

image:
  repository: sandmanacrsandbox.azurecr.io/frontend/sandman-frontend
  tag: latest
  pullPolicy: Always

service:
  port: 30440
  targetPort: 80

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "250m"
    memory: "256Mi"